[package]
name = "verifiable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-where = "1.2"
bounded-collections = { version = "0.1.8", default-features = false }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive","max-encoded-len"] }
scale-info = { version = "2.7.0", default-features = false, features = ["derive"] }
schnorrkel = { version = "0.10.2", default-features = false, features = ["u64_backend"] }
ark-serialize = { version = "0.4", default-features = false, features = ["derive"] }
ark-scale = { version = "0.0.11", default-features = false }
bandersnatch_vrfs = { git = "https://github.com/w3f/ring-vrf.git", branch = "pub-kzg", default-features = false }
fflonk = { git = "https://github.com/w3f/fflonk", default-features = false }
ring = { git = "https://github.com/w3f/ring-proof.git", default-features = false }

[dev-dependencies]
rand_core = "0.6"

[features]
default = [ "std" ]
std = [
  "bounded-collections/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "schnorrkel/std",
  "ark-serialize/std",
  "ark-scale/std",
  "bandersnatch_vrfs/std",
  "fflonk/std",
  "ring/std",
]
